# Copyright (C) 2020-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/google/flame/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/google/flame

PRODUCT_COPY_FILES += \
    vendor/google/flame/proprietary/product/etc/felica/common.cfg:$(TARGET_COPY_OUT_PRODUCT)/etc/felica/common.cfg \
    vendor/google/flame/proprietary/product/lib/lib-imsvideocodec.so:$(TARGET_COPY_OUT_PRODUCT)/lib/lib-imsvideocodec.so \
    vendor/google/flame/proprietary/product/lib64/lib-imsvideocodec.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/lib-imsvideocodec.so
PRODUCT_COPY_FILES += \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Bluetooth_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Codec_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/General_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Global_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Handset_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Hdmi_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Headset_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-f2proto-snd-card/Speaker_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Bluetooth_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Codec_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/General_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Global_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Handset_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Hdmi_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Headset_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/OEM/sm8150-iaxxx-flame-snd-card/Speaker_cal.acdb \
    vendor/google/flame/proprietary/vendor/etc/default_f2proto.mps:$(TARGET_COPY_OUT_VENDOR)/etc/default_f2proto.mps \
    vendor/google/flame/proprietary/vendor/etc/default_flame.mps:$(TARGET_COPY_OUT_VENDOR)/etc/default_flame.mps \
    vendor/google/flame/proprietary/vendor/etc/input_classifier_model.pb:$(TARGET_COPY_OUT_VENDOR)/etc/input_classifier_model.pb \
    vendor/google/flame/proprietary/vendor/etc/maxx_conf_f2proto.ini:$(TARGET_COPY_OUT_VENDOR)/etc/maxx_conf_f2proto.ini \
    vendor/google/flame/proprietary/vendor/etc/maxx_conf_flame.ini:$(TARGET_COPY_OUT_VENDOR)/etc/maxx_conf_flame.ini \
    vendor/google/flame/proprietary/vendor/etc/sensors/config/f2_bmp380.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/f2_bmp380.json \
    vendor/google/flame/proprietary/vendor/etc/sensors/config/f2_lis2mdl.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/f2_lis2mdl.json \
    vendor/google/flame/proprietary/vendor/etc/sensors/config/f2_lis2mdl_dvt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/f2_lis2mdl_dvt.json \
    vendor/google/flame/proprietary/vendor/etc/sensors/config/f2_lis2mdl_evt1_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/f2_lis2mdl_evt1_0.json \
    vendor/google/flame/proprietary/vendor/etc/sensors/config/f2_lis2mdl_evt1_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/f2_lis2mdl_evt1_1.json \
    vendor/google/flame/proprietary/vendor/etc/sensors/config/f2_lsm6dsr.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/f2_lsm6dsr.json \
    vendor/google/flame/proprietary/vendor/etc/sensors/config/f2_sx932x_0_proto_evt1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/f2_sx932x_0_proto_evt1.json \
    vendor/google/flame/proprietary/vendor/etc/sensors/config/f2_tmd3702v.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/f2_tmd3702v.json \
    vendor/google/flame/proprietary/vendor/etc/sensors/config/f2_tmd3702v_dvt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/f2_tmd3702v_dvt.json \
    vendor/google/flame/proprietary/vendor/firmware/OsloSensorPackage.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/OsloSensorPackage.bin \
    vendor/google/flame/proprietary/vendor/firmware/bdwlan-flame-PROTO1.0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan-flame-PROTO1.0.bin \
    vendor/google/flame/proprietary/vendor/firmware/bdwlan-flame-PROTO1.1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan-flame-PROTO1.1.bin \
    vendor/google/flame/proprietary/vendor/firmware/bdwlan-flame.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan-flame.bin \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui.b00 \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui.b01 \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui.b02 \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui.b03 \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui.b04 \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui.b05 \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui.b06 \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui.b07 \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui.mdt \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui_fonts/LeapFrog_Google_Sans_Display_58.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui_fonts/LeapFrog_Google_Sans_Display_58.bin \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui_fonts/LeapFrog_Google_Sans_Display_Medium_37.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui_fonts/LeapFrog_Google_Sans_Display_Medium_37.bin \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui_fonts/LeapFrog_Google_Sans_Display_Medium_52.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui_fonts/LeapFrog_Google_Sans_Display_Medium_52.bin \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui_fonts/LeapFrog_Roboto_37.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui_fonts/LeapFrog_Roboto_37.bin \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui_fonts/LeapFrog_Roboto_42.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui_fonts/LeapFrog_Roboto_42.bin \
    vendor/google/flame/proprietary/vendor/firmware/confirmationui_fonts/LeapFrog_Roboto_52.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/confirmationui_fonts/LeapFrog_Roboto_52.bin \
    vendor/google/flame/proprietary/vendor/firmware/crnv21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv21.bin \
    vendor/google/flame/proprietary/vendor/firmware/ftm5_fw_f2.ftb:$(TARGET_COPY_OUT_VENDOR)/firmware/ftm5_fw_f2.ftb \
    vendor/google/flame/proprietary/vendor/firmware/ftm5_fw_f2_evt1.ftb:$(TARGET_COPY_OUT_VENDOR)/firmware/ftm5_fw_f2_evt1.ftb \
    vendor/google/flame/proprietary/vendor/firmware/ftm5_fw_f2_evt2.ftb:$(TARGET_COPY_OUT_VENDOR)/firmware/ftm5_fw_f2_evt2.ftb \
    vendor/google/flame/proprietary/vendor/firmware/ftm5_fw_f2_p2.ftb:$(TARGET_COPY_OUT_VENDOR)/firmware/ftm5_fw_f2_p2.ftb \
    vendor/google/flame/proprietary/vendor/lib/hw/audio.primary.msmnile.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.msmnile.so \
    vendor/google/flame/proprietary/vendor/lib/sensors.ssc.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.ssc.so \
    vendor/google/flame/proprietary/vendor/lib64/hw/audio.primary.msmnile.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.primary.msmnile.so \
    vendor/google/flame/proprietary/vendor/lib64/sensors.ssc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/sensors.ssc.so
