# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/google/dragon/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/google/dragon/proprietary/bin/tsec_service:system/bin/tsec_service \
    vendor/google/dragon/proprietary/bin/vkinfo:system/bin/vkinfo \
    vendor/google/dragon/proprietary/etc/sysconfig/nexus.xml:system/etc/sysconfig/nexus.xml

PRODUCT_PACKAGES += \
    UserInfoWidget \
    DragonKeyboardFirmwareUpdater \
    GCS \
    HotwordEnrollmentOKGoogleRT5677

PRODUCT_COPY_FILES += \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/acr_ucode.bin:root/vendor/firmware/nouveau/acr_ucode.bin \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/fecs.bin:root/vendor/firmware/nouveau/fecs.bin \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/fecs_sig.bin:root/vendor/firmware/nouveau/fecs_sig.bin \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/gpmu_ucode_desc.bin:root/vendor/firmware/nouveau/gpmu_ucode_desc.bin \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/gpmu_ucode_image.bin:root/vendor/firmware/nouveau/gpmu_ucode_image.bin \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/nv12b_bundle:root/vendor/firmware/nouveau/nv12b_bundle \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/nv12b_fuc409c:root/vendor/firmware/nouveau/nv12b_fuc409c \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/nv12b_fuc409d:root/vendor/firmware/nouveau/nv12b_fuc409d \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/nv12b_fuc41ac:root/vendor/firmware/nouveau/nv12b_fuc41ac \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/nv12b_fuc41ad:root/vendor/firmware/nouveau/nv12b_fuc41ad \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/nv12b_method:root/vendor/firmware/nouveau/nv12b_method \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/nv12b_sw_ctx:root/vendor/firmware/nouveau/nv12b_sw_ctx \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/nv12b_sw_nonctx:root/vendor/firmware/nouveau/nv12b_sw_nonctx \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/pmu_bl.bin:root/vendor/firmware/nouveau/pmu_bl.bin \
    vendor/google/dragon/proprietary/root/vendor/firmware/nouveau/pmu_sig.bin:root/vendor/firmware/nouveau/pmu_sig.bin \
    vendor/google/dragon/proprietary/root/vendor/firmware/nvidia/tegra210/bpmp.bin:root/vendor/firmware/nvidia/tegra210/bpmp.bin \
    vendor/google/dragon/proprietary/root/vendor/firmware/nvidia/tegra210/nvdec_bl_prod.bin:root/vendor/firmware/nvidia/tegra210/nvdec_bl_prod.bin \
    vendor/google/dragon/proprietary/root/vendor/firmware/nvidia/tegra210/nvdec_ns.bin:root/vendor/firmware/nvidia/tegra210/nvdec_ns.bin \
    vendor/google/dragon/proprietary/root/vendor/firmware/nvidia/tegra210/nvdec_prod.bin:root/vendor/firmware/nvidia/tegra210/nvdec_prod.bin \
    vendor/google/dragon/proprietary/root/vendor/firmware/nvidia/tegra210/xusb.bin:root/vendor/firmware/nvidia/tegra210/xusb.bin

